### ISSUE TITLE
Use PolKit

### ISSUE THREAD

**Issue by ZanderBrown** [raspberrypi-ui/pipanel#7]
Make use of PolKit to authenticate operations requiring root privileges.

For example PolKit is used in Add / Remove Software to confirm package installation.

The simplest way to make use of it here would be to prefix commands requiring such privileges with `pkexec`

**Comment by waveform80** [comment]
I should've looked at the issues list first! Just spent a good 10 minutes trawling through the code and the changesets to determine why pipanel was seemingly locking up on my Pi. As it turns out it was because pipanel was [spawning a "sudo cp" process](https://github.com/raspberrypi-ui/pipanel/blob/master/src/pipanel.c#L703) which was hanging around waiting for a password (because I'd disabled the NOPASSWD option for my non-pi user). Looks like 2f5af06d455fb8fad301817cf9db5b43c4e0a778 (from yesterday) is an attempt to alleviate that by using "sudo  -A cp" (which will fail if an askpass style program isn't available) but the return code of the `system` call is ignored in that case which probably isn't ideal.

`pkexec` does look like an attempt to support `sudo` like functionality in a GUI environment, plus it's installed by default on Raspbian (`raspberrypi-ui-mods` depends on `policykit-1`). That said, it doesn't seem to like my environment much (trying `pkexec pipanel` for example fails with a "cannot open display" error). Not the end of the world if it's just used for `cp` but perhaps worth looking at.

Anyway, I'd suggest checking the return code of `system()` at the very least :)

**Comment by ZanderBrown** [comment]
Interesting that it would fail, does the likes of `pkexec leafpad` work? Or Add / Remove Software?

**Comment by waveform80** [comment]
Afraid not: same error "cannot open display" (that's after `pkexec` prompts for user credentials). I should mention my setup is in some ways thoroughly non-standard, hence why pipanel hung for me with its current `sudo` setup:

1. I remove the NOPASSWD option from the "pi" user (and change the password)
2. I add an sssd setup so my Pis can do authentication via my LDAP server (I freely admit this is overkill but I had one anyway, so what the hell!); that said the "pi" user remains strictly local (authenticated via pam_unix) and when testing `pkexec` above I made sure to test under the local "pi" user (partially because I had to: pkexec doesn't seem to notice any of the LDAP users :)

Still, ignore my weird setup - it's definitely niche. If it works without that, I'd say go for `pkexec` (though I might then be tempted to go nag the policykit project about their support for non-standard authnz configurations!)

**Comment by ZanderBrown** [comment]
Okay I think we can assume it's your (rather non standard) setup then, always worked fine for me on multiple distros on multiple devices (including the Pi of course)

**Comment by waveform80** [comment]
Hmmm, I was certain you were right (my setup is definitely weird and thus not to be trusted for things like this) but I just grabbed a relatively fresh SD card containing Raspbian (the 2017-04-10 image; okay, not exactly the latest but hardly ancient either). Tried `pkexec pipanel` from a terminal and got the same result: "cannot open display:" (after attempting to authenticate as "pi"). Not sure what's going on there ($DISPLAY is definitely set to :0.0, as one would expect, but executing `pkexec sh -c 'echo DISPLAY=$DISPLAY'` shows "DISPLAY=").

**Comment by ZanderBrown** [comment]
Just to be clear you are running these commands from LXTerminal on the PIXLE desktop (don't know what else you would be doing but just to be certain)

**Comment by spl237** [comment]
First off, just to say that pulling stuff at random from my GitHub repos isn't a great idea - there's no guarantee that code in here is a) finished or b) tested; I'd suggest waiting until we actually release debs!

The recent changes are indeed an attempt to deal with the situation where a user has disabled passwordless sudo. They include the installation of a Zenity script as the askpass program (data/pwdpic.sh); for piclone it also requires a change to sudo behaviour to allow a timestamp to persist across multiple system calls.

I did originally look at using polkit to do this, but I seem to recall there were problems with it asking multiple times for authentication, which just got annoying. It may be that the fix I found for sudo doing the same thing will also fix this for pkexec - I'd have to try it to find out.

**Comment by spl237** [comment]
From the pkexec manual:

"The environment that PROGRAM will run in will be set to a minimal known and safe environment in order to avoid injecting code through LD_LIBRARY_PATH or similar mechanisms. In addition the PKEXEC_UID environment variable is set to the user id of the process invoking pkexec. As a result, pkexec will not allow you to run e.g. X11 applications as another user since the $DISPLAY environment variable is not set."

So Dave, looks as if by design pkexec can't do what you want.

**Comment by ZanderBrown** [comment]
It's perfectly possible to run the [whole application through `pkexec`](https://unix.stackexchange.com/a/203149) with a policy file and pkexec prefixed desktop file [as synaptic has done since wheezy](http://bazaar.launchpad.net/~synaptic-developers/synaptic/trunk/view/head:/data/com.ubuntu.pkexec.synaptic.policy.in)

**Comment by spl237** [comment]
You can't run the whole application with root permissions, as this causes GVolumeManager, which is used to determine what drives are available, to use the system DBus rather than the session DBus. (GVolumeManager doesn't work with the system DBus, and there is no workaround for this.) So you have to run each individual system call from the applicationwith root permissions, rather than running the entire application as root. sudo -A works for this - I am not convinced that polkit has any advantage over sudo -A for this purpose. (sudo -A is certainly better than gksudo, as that screws up when you try to pipe an argument into commands, as I have to do for fdisk...) Given this approach (sudo -A) works, I'm not going to change it unless there is a compelling reason to do so.

**Comment by ZanderBrown** [comment]
Apart from the visual niceties of being consistent with other applications, use of PolKit thought pkexec doesn't provide all that much.

However if a PolKit Action was setup correctly a sysadmin could block access to certain settings (see gnome-control-center) something that may be increasing relevant with the growth of PIXLE x86

Please note this is the pipanel repository, not piclone.

**Comment by waveform80** [comment]
> Just to be clear you are running these commands from LXTerminal on the PIXLE desktop (don't know what else you would be doing but just to be certain)

@ZanderBrown 
Yup.

> From the pkexec manual:
>
> "The environment that PROGRAM will run in will be set to a minimal known and safe environment in order to avoid injecting code through LD_LIBRARY_PATH or similar mechanisms. In addition the PKEXEC_UID environment variable is set to the user id of the process invoking pkexec. As a result, pkexec will not allow you to run e.g. X11 applications as another user since the $DISPLAY environment variable is not set."
>
> So Dave, looks as if by design pkexec can't do what you want.

Ah, that explains it - thanks! I should've read that page more thoroughly!

> First off, just to say that pulling stuff at random from my GitHub repos isn't a great idea - there's no guarantee that code in here is a) finished or b) tested; I'd suggest waiting until we actually release debs!

@spl237 
Sorry, I wasn't clear: I haven't actually tried anything in the repo, just came by trying to understand why `pipanel` was appearing to lock-up on my non-passwordless (erm... passworded? Hmm, sounds weird too) configuration and found this seemingly related issue (after stumbling across the aforementioned commit). As I understand the issue, and that it's effectively dealt with, I will indeed just wait for the debs (I've just set the development Pi back to passwordless for now).

> You can't run the whole application with root permissions, as this causes GVolumeManager, which is used to determine what drives are available, to use the system DBus rather than the session DBus. (GVolumeManager doesn't work with the system DBus, and there is no workaround for this.) So you have to run each individual system call from the applicationwith root permissions, rather than running the entire application as root. sudo -A works for this - I am not convinced that polkit has any advantage over sudo -A for this purpose. (sudo -A is certainly better than gksudo, as that screws up when you try to pipe an argument into commands, as I have to do for fdisk...) Given this approach (sudo -A) works, I'm not going to change it unless there is a compelling reason to do so.

Sounds good to me. The only thing I'd advocate is that it's probably worth checking the result of the call. My concern about the call failing when no askpass is available is obviously irrelevant in light of:

> ... They include the installation of a Zenity script as the askpass program ...

However, what happens if the user fails to authenticate, or the copy fails for another reason? Might be worth an error message?

**Comment by ZanderBrown** [comment]
> Sounds good to me. The only thing I'd advocate is that it's probably worth checking the result of the call. My concern about the call failing when no askpass is available is obviously irrelevant in light of:
> > ... They include the installation of a Zenity script as the askpass program ...
>
> However, what happens if the user fails to authenticate, or the copy fails for another reason? Might be worth an error message?

Of course this is largely to point of using PolKit, in most implementations (including LXPolKit) you get anther attempt entering the password, with no extra work from the client programs perspective.

**Comment by waveform80** [comment]
> Of course this is largely to point of using PolKit, in most implementations (including LXPolKit) you get anther attempt entering the password, with no extra work from the client programs perspective.

sudo more or less provides the same service; it may call the askpass script several times but from the point of view of the thing calling sudo (i.e. pipanel) it's still only had to make one call. Besides which, this doesn't counter the other (rather more important) issues Simon's raised above about using polkit in this case (particularly system v session DBus access).

**Comment by ZanderBrown** [comment]
Simons point was that you couldn't run the whole of piclone under pkexec, however a single PolKit Action just for saving greeter settings in pipanel is exactly what PolKit is designed for

**Comment by waveform80** [comment]
Granted - but to address Simon's other query, what tangible benefit does PolKit offer over classic sudo in this scenario?
